# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7secoekErEAvZ-_Rt4SNR1zK1i6EtLT

# Import Required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import plotly.express as px
import plotly.graph_objects as go

"""# Load Dataset"""

df = pd.read_csv("/content/sample_data/credit_card_fraud_10k[1].csv")
print(df.head())
print(df.info())
print(df.isnull().sum())

"""# Remove Duplicate Records"""

df = df.drop_duplicates()
print("Dataset Shape:", df.shape)
print(df.describe())

"""# Fraud vs Normal Transaction Count"""

fraud_count = df['is_fraud'].value_counts()
print(fraud_count)

"""# Fraud Distribution Visualization"""

plt.figure(figsize=(6,4))
sns.countplot(x='is_fraud', data=df)
plt.title("Fraud vs Normal Transactions")
plt.xlabel("is_fraud")
plt.ylabel("Count")
plt.show()

"""# Transaction Amount Distribution"""

plt.figure(figsize=(8,5))

sns.histplot(df['amount'], bins=50, kde=True)

plt.title("Transaction Amount Distribution")

plt.xlabel("Amount")

plt.show()

"""# Boxplot for Outlier Detection"""

plt.figure(figsize=(8,5))
sns.boxplot(x=df['amount'])
plt.title("Transaction Amount Outliers")
plt.show()

"""# Correlation Heatmap"""

plt.figure(figsize=(12,10))

sns.heatmap(df.corr(numeric_only=True), cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

"""# Fraud vs Transaction Amount Analysis"""

plt.figure(figsize=(8,5))
sns.boxplot(x='is_fraud', y='amount', data=df)
plt.title("Fraud vs Transaction Amount")
plt.show()

"""# Risk Analysis Function"""

def risk_category(amount):
    if amount < 100:
        return "Low Risk"
    elif amount < 1000:
        return "Medium Risk"
    else:
        return "High Risk"

"""# Create Risk Level Column"""

df['Risk_Level'] = df['amount'].apply(risk_category)

print(df['Risk_Level'].value_counts())
X = df[['transaction_hour']]
y = df['amount']

"""# Split Training and Testing Data"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""# Create Linear Regression Model"""

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

"""# R² Score"""

score = r2_score(y_test, y_pred)

print("R2 Score:", score)

"""# Residual Analysis"""

residuals = y_test - y_pred

plt.figure(figsize=(8,5))

plt.scatter(y_pred, residuals)

plt.axhline(y=0, color='r')

plt.title("Residual Analysis")

plt.xlabel("Predicted Values")

plt.ylabel("Residuals")

plt.show()

"""# Plotly Fraud Distribution Dashboard"""

fig1 = px.histogram(
    df,
    x='is_fraud',
    title='Fraud vs Normal Transactions'
)

fig1.show()

"""# Plotly Transaction Amount Distribution"""

fig2 = px.histogram(
    df,
    x='amount',
    nbins=50,
    title='Transaction Amount Distribution'
)

fig2.show()

"""# Scatter Plot"""

fig3 = px.scatter(
    df,
    x='transaction_hour',
    y='amount',
    color='is_fraud',
    title='Transaction Time vs Amount'
)

fig3.show()

"""# Risk Level Distribution"""

fig4 = px.histogram(
    df,
    x='Risk_Level',
    color='Risk_Level',
    title='Risk Level Distribution'
)

fig4.show()

"""# Output Message"""

print("Project Execution Completed Successfully")